version: '3.8'

services:
  landing:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: presentai-landing
    restart: unless-stopped
    
    # Security: Non-root user
    user: "1001:1001"
    
    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    
    # Health monitoring
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:3000/ || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    
    # Environment configuration
    environment:
      # Node.js environment
      NODE_ENV: production
      
      # Nuxt runtime config - connect to pocketbase service
      NUXT_PUBLIC_POCKETBASE_URL: ${NUXT_PUBLIC_POCKETBASE_URL:-http://pocketbase:8080}
      
      # Optional: Custom app URL
      NUXT_PUBLIC_APP_URL: ${NUXT_PUBLIC_APP_URL:-http://localhost:3000}
    
    # Port binding
    ports:
      - "3000:3000"
    
    # Security options
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE

# Optional: Network to connect with pocketbase
networks:
  default:
    name: presentai-network
    external: false